### ISSUE TITLE
图片垂直居中写法

### ISSUE THREAD

**Issue by jozhi** [jozhi/jozhi.github.com#4]
方法一 (XHTML 1.0 transitional)：

该方法是将外部容器的显示模式设置成display:table，img标签外部再嵌套一个span标签，并设置span的显示模式为display:table-cell，这样就可以很方便的使用vertical-align象表格元素那样对齐了，当然这只是在标准浏览器下，IE6/IE7还得使用定位。

HTML结构部分：

``` html
<div id="box">
    <span><img src="images/demo.jpg" alt=""></span>
</div>
```

CSS样式部分：

``` css
#box{
    width:500px;height:400px;
    overflow:hidden;
    position:relative;
    display:table-cell;
    text-align:center;
    vertical-align:middle;
    border:1px solid #d3d3d3;background:#fff;
}
#box span{
    position:static;
    *position:absolute; /*针对IE6/7的Hack*/
    top:50%; /*针对IE6/7的Hack*/
}
#box img {
    position:static;
    *position:relative; /*针对IE6/7的Hack*/
    top:-50%;left:-50%; /*针对IE6/7的Hack*/
    border:1px solid #ccc;
}
```

该方法有个弊端，在标准浏览器下由于外部容器#box的显示模式为display:table-cell，所以导致#box无法使用margin属性，并且在IE8下设置边框也无效。​

方法二 (XHTML 1.0 strict)：

标准浏览器还是将外部容器#box的显示模式设置为display:table-cell，IE6/IE7是利用在img标签的前面插入一对空标签的办法。

HTML结构部分：

``` html
<div id="box">
   <i></i><img src="images/demo.jpg" alt="img">
</div>
```

CSS样式部分：

``` css
#box{
    width:500px;height:400px;
    display:table-cell;
    text-align:center;
    vertical-align:middle;
    border:1px solid #d3d3d3;background:#fff;
}
#box img{
    border:1px solid #ccc;
}
```

``` html
<!--[if IE]>
    <style type="text/css">
    #box i {
        display:inline-block;
        height:100%;
        vertical-align:middle
        }
    #box img {
        vertical-align:middle
        }
    </style>
<![endif]-->
```

方法2也同样适用XHTML 1.0 transitional。以上方法都是收集于脚本之家，暂时只对这2个方法比较满意，兼容性方面不错，使用起来的限制也比较小，还有些方法我也都一一测试过，效果都不理想，在各浏览器中的差异比较大。另外司徒正美这里也收集了一些方法。
思考：很多方法都是依赖于将外部容器的显示模式设置成table才能实现垂直居中，也就是div来模拟table，如果CSS有一个属性来实现这种效果那该多好。如果你也有好的方法，欢迎你来分享。​

另外还有 DOM 容器垂直居中方法一枚：

``` html
<div class="wrap">
   <div class="hack">
      <div class="cnt"> content </div>
   </div>
</div>
```

``` css
/* CSS 部分的代码实现：整体代码参见上述 demo*/
.wrap{
    width:500px;height:300px;border:3px solid #ddd;margin:0 auto;padding:20px;display:table;
    *position:relative;
}
.hack{
    display:table-cell;vertical-align:middle;
    *position:absolute;*top:50%;
}
.cnt{
    *position:relative;*top:-50%;
}
```
