### ISSUE TITLE
Css 属性书写顺序

### ISSUE THREAD

**Issue by jozhi** [jozhi/jozhi.github.com#5]
<p>刚开始从业时期 CSS 语法风格多变，从比较标准的写法到横排写法再到现在。中间差不多花有一年多两年时间才基本定型，此时要感谢锟哥、勇哥以及当年的竹子与鸟窝群。</p>

<p>这个文件要描述的是 css 的属性书写顺序，是 <span title='10年左右'>当年</span> <em>火星人</em> 分享出来的，在这里对他表示感谢。这里我把这份儿文档分享出来希望能够对大家有所帮助。</p>

<p>其实没有必要严格，基本上按照DOM的box模型从内到外的顺序来写就可以，方便查阅、修改</p>

``` css
el {
     display: ;
     visibility: ;
     float: ;
     clear:;

     position: ;
     top: ;
     right: ;
     bottom:;
     left: ;
     z-index:;

     width: ;
     min-width:;
     max-width: ;
     height: ;
     min-height: ;
     max-height: ;
     overflow: ;

     margin: ;
     margin-top: ;
     margin-right: ;
     margin-bottom: ;
     margin-left: ;

     padding: ;
     padding-top: ;
     padding-right: ;
     padding-bottom: ;
     padding-left: ;

     border: ;
     border-top: ;
     border-right: ;
     border-bottom: ;
     border-left: ;

     border-width: ;
     border-top-width: ;
     border-right-width: ;
     border-bottom-width: ;
     border-left-width: ;

     border-style: ;
     border-top-style: ;
     border-right-style: ;
     border-bottom-style: ;
     border-left-style: ;

     border-color: ;
     border-top-color: ;
     border-right-color: ;
     border-bottom-color: ;
     border-left-color: ;

     outline: ;

     list-style: ;

     table-layout: ;
     caption-side: ;
     border-collapse: ;
     border-spacing: ;
     empty-cells: ;

     font: ;
     font-family: ;
     font-size: ;
     line-height: ;
     font-weight: ;
     text-align: ;
     text-indent: ;
     text-transform: ;
     text-decoration: ;
     letter-spacing: ;
     word-spacing: ;
     white-space: ;
     vertical-align: ;
     color: ;

     background: ;
     background-color: ;
     background-image: ;
     background-repeat: ;
     background-position: ;

     opacity: ;

     cursor: ;

     content: ;
     quotes: ;
}

```
